services:
  web:
    image: node
    command: npm start
    ports:
      - "8000:4242"
    links:
      - db
    working_dir: /src
    environment:
      SEQ_DB: mydatabase
      SEQ_USER: username
      SEQ_PW: pgpassword
      PORT: 4242
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./:/src
  db:
    image: postgres
    ports:
    - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres